version: '3'
services:
  sdaas:
    build: ./sdaas
    image: copernicani/data-budget-sdaas:$databudgetversion
    ports:
      - "9999:8080"
  api:
    build: ./apis
    image: copernicani/data-budget-api:$databudgetversion

    ports:
      - "8080:80"
    depends_on:
      - "sdaas"
  lodview:
    build: ./lodview
    image: copernicani/data-budget-lodview:$databudgetversion
    ports:
      - "8082:8080"
    depends_on:
      - "sdaas"
  lode:
    build: ./g0v-ap
    image: copernicani/data-budget-lode:$databudgetversion
    ports:
      - "8083:8080"
  router:
    build: ./router
    image: copernicani/data-budget-router:$databudgetversion
    ports:
      - "80:80"
    depends_on:
      - "sdaas"
      - "lodview"
      - "lode"
      - "api"
